name: perl-math-gsl-macos
on:
    push:
      branches:
      - '*'
    pull_request:
        branches:
        - '*'
    workflow_dispatch:
jobs:
  build-perl:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.40'
    - name: Install Math::GSL
      run: cpanm -v Math::GSL
